[workspace]
members = [
  "l1-1",
  "l1-2",
  "l1-5",
  "l1-6",
  "l1-7",
  "l1-8",
  "l1-9",
  "l2-1",
  "l2-3",
  "l2-4",
  "l2-5",
  "l2-6",
  "l2-7",
  "l2-9",
  "l2-10",
  "l2-11",
  "l2-12",
  "l2-13",
  "l2-15",
  "l2-17",
  "l2-20",
  "l2-21",
  "l2-22",
]
